[project]
name = "home-profant-eu"
version = "0.1.0"
description = "home portal for profant.eu"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
